server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
            
        - id: ai-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=0
            
        - id: gateway-health
          uri: http://localhost:8080
          predicates:
            - Path=/health
          filters:
            - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
